### ISSUE TITLE
findOne for API without id

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#121]
Hello @frank06 again,

If I understand correctly, for findOne, we need to pass an id.
But many APIs are designed without using id (backend reads the id from access token), for example: /api/me

1. What will happen if we don't pass the id? 
2. Will the library store data locally successfully in this case?

**Comment by frank06** [comment]
Local storage needs a type. Which model/type is the data returned by `/api/me`, can you show an example?

**Comment by thphuc** [comment]
Hi @frank06 

That could be a json that contains the user info:

```
{
    "id": "1234",
    "name": "Phuc"
}
```

Also, I have questions with findAll:

1. If we call findAll multiple times, will new data override old data on local database?
2. Does the library handle pagination? Ex: page 1 we load 100 items, page 2 we load another 100 items -> local database will have 200 records? And next time user open the app, we reload 100 items (page 1), will this 100 new items override 100 (or 200) items on local?

Thanks a lot!

**Comment by frank06** [comment]
Something like the following, in an adapter on the `User` model:

```dart
  Future<User?> get currentUser async {
    return sendRequest(
      baseUrl.asUri / 'me',
      onSuccess: (data) {
        return deserialize(data as Map<String, dynamic>).model;
      },
    );
  }
```

Regarding `findAll`:

New data will override old data on a type/id basis.

If a first call to `findAll` returns data for ids `1`, `2`, `3` and a second call updated data for `2`, `3`, `4` you will end up in your local storage with: `1`, `2` (updated), `3` (updated) and `4`.

If you want your local storage to mirror the latest call (i.e. delete id `1`), pass `syncLocal: true`. This can be used to reflect server-side deletions.

So in your pagination example if the first 100 records are different from the second 100 records and `syncLocal` is `false` (default) then yes you will end up with 200 records.  When you reload the first 100 for page 1, only these will be updated in local storage but you will still have 200 in local storage (and in your widgets, because FD watchers always only reflect local storage contents).

**Comment by thphuc** [comment]
Hi @frank06 that sounds great. Thank you!

**Comment by frank06** [comment]
@thphuc In case you're interested the new documentation site is live: https://flutterdata.dev/

**Comment by thphuc** [comment]
Thanks @frank06 for sharing. Awesome!
