### ISSUE TITLE
Question: When POST request will be synced to remote

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#128]
Hello again.

We are testing **save** method. I turned off the connection when calling this **save** method.
Then I turned it on, wait for a while. However, I can not see the data synced to remote.

Can you let me know when the sync will be triggered? @frank06

**Comment by frank06** [comment]
@thphuc you need to manually call `retry`.

Have a look at this to get you in the right direction: https://flutterdata.dev/articles/how-to-retry-offline-sync-data/

**Comment by aviqbaihaqy** [comment]
how to implement this, can you give an example

**Comment by ariejan** [comment]
@frank06 the instructions from last year seem outdated, is that correct? If you can give a few pointers I ca update the website article to reflect the current situation.

**Comment by frank06** [comment]
@ariejan you're right, I changed this and did not update the docs. FD is now taking care of the retries, should improve this so that we can adjust the behavior.

This is how we're using it:

```
final _sub = ref.listen(offlineRetryProvider, (_, __) {});

ref.onDispose(() {
  _sub.close();
});
```

**Comment by HeinKoZin** [comment]
Could someone please give me a full example? I'm new to aflutter.

**Comment by frank06** [comment]
@HeinKoZin I just posted the code above that you can use anywhere in your app where you want the retries to happen. It could be on [initialization](https://flutterdata.dev/docs/initialization/). What did you try?

**Comment by andreystavitsky** [comment]
@frank06 there's no onDispose on WidgetRef ref

**Comment by frank06** [comment]
@andreystavitsky Why would you put that code in a widget that gets repainted and disposed an arbitrary number of times? You want to listen once, keep listening throughout the lifespan of the user's session and eventually dispose (on log out, for example). So that should go inside a long-lived provider (on initialization for example) where `ref` is of type `ProviderRef`

**Comment by andreystavitsky** [comment]
> Why would you put that code in a widget that gets repainted and disposed an arbitrary number of times?

because I'm new in Riverpod, I'm always used Bloc, and it's a bit complicated to go through all nuances of some library without examples.
Unfortunately there is a lack of not outdated documentation\comments in source code\somewhat else to explain how do all the things work in different situations.

Thank you for your answers, now I'm understand how to use offline retry.

**Comment by frank06** [comment]
If using Riverpod here's an example (untested):

You can do this in your `Scaffold`

```dart
child: ref.watch(initializerProvider).when(
   error: (error, _) => Text(error.toString()),
   loading: () => const CircularProgressIndicator(),
   data: (_) => Text('App boot is ready, replace me with main UI widget'),
  ),
),
```

Then define your initializer where you initialize any number of services needed to display the main widget of your UI:

```dart
final initializerProvider = FutureProvider<bool>((ref) async {
  // initialize FD
  await ref.container.refresh(repositoryInitializerProvider.future);
  
  // initialize other services
  
  // retry offline events
  final _sub = ref.listen(offlineRetryProvider, (_, __) {});
  
  // close offline retry subscription
  ref.onDispose(() {
    _sub.close();
  });
});
```

You could also place this offline retry logic in some more specific place (for example when a user logs in, and close the sub when the user logs out)
