### ISSUE TITLE
Persistent offlineRetryProvider between sessions

### ISSUE THREAD

**Issue by InspectlyMads** [flutterdata/flutter_data#280]
The 'offlineRetryProvider' uses the internal repositories to find offline operations, and the retry works perfectly when transitioning from offline to online within the same session. However, creating data offline, closing the app, and then reopening it with an internet connection does not automatically trigger the retry logic for the previously saved offline operations. I know I can manage this manually by iterating through my repositories and adding an 'isSynced' flag to all my models, but I was hoping it would be possible for the offline operations to be saved across sessions somehow.

On a side note, I would like to know if you have a community Discord or Slack. I have thoroughly read your documentation but still have some questions. My company is about to start an 'Offline First' project, and we are currently exploring our options in existing frameworks. Also, do you recommend waiting for v2, or will it be easy enough to migrate when it is ready?

**Comment by frank06** [comment]
Sorry for the late response! You are right about `offlineRetryProvider`. Actually it has been removed in v2 to push specific implementations to user-space (primitives will keep being supported). It also needs thorough testing.

Appreciate the fact that you were considering Flutter Data for your project. I created and have been maintaining this package since 2019 but I had some personal issues and had to step away for a few months. At the moment I am unsure about my future involvement here but I'm talking to someone who could potentially carry on. Honestly v2 has a significant amount of changes, I'll try to keep the API as unchanged as possible, but I'm not sure how easy it will be to migrate. A Slack community is a great idea, actually.
