### ISSUE TITLE
dio support?

### ISSUE THREAD

**Issue by ac130kz** [flutterdata/flutter_data#70]
I'm not sure whether it's possible to override the default http client by dio, you mentioned it in https://github.com/flutterdata/flutter_data/issues/1. If you can show an example, I'll be really grateful.

P.S. I'm also surprised that you don't apply [compute() background processing](https://flutter.dev/docs/cookbook/networking/background-parsing) for json decoding/encoding.

**Comment by frank06** [comment]
Curious, what are the advantages of using Dio in Flutter Data? If there are good ones I'd be open to a pull request.

Parsing JSON with `compute()` can make the process slower because of the overhead of communicating with an isolate. It's probably a good idea for very big payloads that cause the UI to freeze. If you need it, you can override `sendRequest` and use it!

**Comment by ac130kz** [comment]
> what are the advantages of using Dio in Flutter Data?

I find interceptors, file uploads/streams easier to implement, than using the default client's API

> a good idea for very big payloads

Good to know! I'll try to implement a threshold, I see some evidence in the Flutter framework [itself](https://github.com/flutter/flutter/blob/183fe75d58131c10a4abb920c4d540c877c9e897/packages/flutter/lib/src/services/asset_bundle.dart#L74)

**Comment by frank06** [comment]
Dio interceptors are a direct competitor to Flutter Data adapters. That said, they can both perfectly coexist. For now, won't fix.
