### ISSUE TITLE
CRUD urls on web

### ISSUE THREAD

**Issue by christianmds** [flutterdata/flutter_data#82]
When making a request on mobile, our API is being hit with `GET /users/123` which is what we want. However on web, it's instead `OPTIONS /http://localhost:46843/users/123`. For some reason the url the app is being served from (`localhost:46843`) gets injected into the request url.

It may be important to know that we have overridden the `baseDirFn` parameter of the `configureRepositoryLocalStorage()` method to return an empty string since `path_provider` isn't supported on web. This is the error we get when we don't override: `Error: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

Is this the best way to get around the error?

We've also tested the [todos app](https://github.com/flutterdata/flutter_data_todos) on web (again overriding `baseDirFn`), but we get the same result.

**Comment by andreacioni** [comment]
It could be a CORS related issue. I had the same problem when I moved to Flutter Web, you have to add an handler on your CRUD API to respond with an appropriate `Access-Control-Allow-Origin` to every OPTIONS request. It migth be `Access-Control-Allow-Origin: *` in _non-productive_ environment.

**Comment by tmartineau** [comment]
No it's not CORS (I am working on the project with @christianmds) the problem is that the url that flutter_data is calling is injecting the domain that the web project is running on. For example the local API is running on `localhost:3000` but flutter_data is calling `http://localhost:3000/http://localhost:46843/users/123`. In this example the web app is running on `localhost:46843`. CORS is not coming up as an issue... infact the call is happenign no problem and is 404ing... because there is no route that starts with `/http://localhost:46843/...`. And again to be clear this is not an issue when running on mobile.

**Comment by frank06** [comment]
Interesting... that definitely looks like a bug. Last time I tested on web was months ago and that didn't seem to be an issue with the Todos app, but it's very possible that stopped working.

Unfortunately I won't have time to look at this for at least 2 weeks. If you manage to find out, I'll happily review a PR.

**Comment by tmartineau** [comment]
@frank06 thanks for the response... I think we narrowed it down to the `path_helper.canonicalize` that happens in the `/` operator in the extensions file.

```
Uri operator /(String path) {
    if (path == null) return this;
    return replace(path: path_helper.canonicalize('/${this.path}/$path'));
  }
```

Seems that `path.canonicalize` is doing some stuff in the `absolute` method that inserts `current` into the string which according to the comments "On the browser, [style] defaults to [Style.url] and [current] defaults to the current URL.".

Not sure what the solution is here though since the addition of the host is happening within path library (and we do not have much experience digging around in there)... is canonicalize needed if the environement is web?

**Comment by christianmds** [comment]
After a bit of experimenting, it looks like using `normalize` over `canonicalize` removes `http://localhost:46843/` from the request url: `return replace(path: path_helper.normalize('/${this.path}/$path'));`

Our experience is pretty limited in this area, so we don't know the differences between `canonicalize` and `normalize`, or if this would end up breaking other things.
